create table cidade (id  integer, nome varchar(80) not null, estado_id bigint not null, primary key (id))
create table cozinha (id  integer, nome varchar(60) not null, primary key (id))
create table estado (id  integer, nome varchar(80) not null, primary key (id))
create table forma_pagamento (id  integer, descricao varchar(255) not null, primary key (id))
create table grupo (id  integer, nome varchar(255) not null, primary key (id))
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null)
create table item_pedido (id  integer, observacao varchar(255), preco_total numeric(19,2) not null, preco_unitario numeric(19,2) not null, quantidade integer not null, pedido_id bigint not null, produto_id bigint not null, primary key (id))
create table pedido (id  integer, codigo varchar(255) not null, data_cancelemento datetime, data_confirmacao datetime, data_criacao datetime not null, data_entrega datetime, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), status integer, subtotal numeric(19,2) not null, taxa_frete numeric(19,2) not null, valor_total numeric(19,2) not null, usuario_cliente_id bigint not null, endereco_cidade_id bigint, forma_pagamento_id bigint not null, restaurante_id bigint not null, primary key (id))
create table permissao (id  integer, descricao varchar(255) not null, nome varchar(255) not null, primary key (id))
create table produto (id  integer, ativo boolean not null, descricao varchar(255) not null, nome varchar(255) not null, preco numeric(19,2) not null, restaurante_id bigint not null, primary key (id))
create table restaurante (id  integer, aberto boolean, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, taxa_frete numeric(19,2) not null, cozinha_id bigint not null, endereco_cidade_id bigint, primary key (id))
create table restaurante_forma_pagamento (restaurante_id bigint not null, forma_pagamento_id bigint not null)
create table usuario (id  integer, data_cadastro datetime not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id))
create table usuario_grupo (usuario_id bigint not null, grupo_id bigint not null)
create table cidade (id  integer, nome varchar(80) not null, estado_id bigint not null, primary key (id))
create table cozinha (id  integer, nome varchar(60) not null, primary key (id))
create table estado (id  integer, nome varchar(80) not null, primary key (id))
create table forma_pagamento (id  integer, descricao varchar(255) not null, primary key (id))
create table grupo (id  integer, nome varchar(255) not null, primary key (id))
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null)
create table item_pedido (id  integer, observacao varchar(255), preco_total numeric(19,2) not null, preco_unitario numeric(19,2) not null, quantidade integer not null, pedido_id bigint not null, produto_id bigint not null, primary key (id))
create table pedido (id  integer, codigo varchar(255) not null, data_cancelemento datetime, data_confirmacao datetime, data_criacao datetime not null, data_entrega datetime, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), status integer, subtotal numeric(19,2) not null, taxa_frete numeric(19,2) not null, valor_total numeric(19,2) not null, usuario_cliente_id bigint not null, endereco_cidade_id bigint, forma_pagamento_id bigint not null, restaurante_id bigint not null, primary key (id))
create table permissao (id  integer, descricao varchar(255) not null, nome varchar(255) not null, primary key (id))
create table produto (id  integer, ativo boolean not null, descricao varchar(255) not null, nome varchar(255) not null, preco numeric(19,2) not null, restaurante_id bigint not null, primary key (id))
create table restaurante (id  integer, aberto boolean, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, taxa_frete numeric(19,2) not null, cozinha_id bigint not null, endereco_cidade_id bigint, primary key (id))
create table restaurante_forma_pagamento (restaurante_id bigint not null, forma_pagamento_id bigint not null)
create table usuario (id  integer, data_cadastro datetime not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id))
create table usuario_grupo (usuario_id bigint not null, grupo_id bigint not null)
create table cidade (id  integer, nome varchar(80) not null, estado_id bigint not null, primary key (id))
create table cozinha (id  integer, nome varchar(60) not null, primary key (id))
create table estado (id  integer, nome varchar(80) not null, primary key (id))
create table forma_pagamento (id  integer, descricao varchar(255) not null, primary key (id))
create table grupo (id  integer, nome varchar(255) not null, primary key (id))
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null)
create table item_pedido (id  integer, observacao varchar(255), preco_total numeric(19,2) not null, preco_unitario numeric(19,2) not null, quantidade integer not null, pedido_id bigint not null, produto_id bigint not null, primary key (id))
create table pedido (id  integer, codigo varchar(255) not null, data_cancelemento datetime, data_confirmacao datetime, data_criacao datetime not null, data_entrega datetime, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), status integer, subtotal numeric(19,2) not null, taxa_frete numeric(19,2) not null, valor_total numeric(19,2) not null, usuario_cliente_id bigint not null, endereco_cidade_id bigint, forma_pagamento_id bigint not null, restaurante_id bigint not null, primary key (id))
create table permissao (id  integer, descricao varchar(255) not null, nome varchar(255) not null, primary key (id))
create table produto (id  integer, ativo boolean not null, descricao varchar(255) not null, nome varchar(255) not null, preco numeric(19,2) not null, restaurante_id bigint not null, primary key (id))
create table restaurante (id  integer, aberto boolean, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, taxa_frete numeric(19,2) not null, cozinha_id bigint not null, endereco_cidade_id bigint, primary key (id))
create table restaurante_forma_pagamento (restaurante_id bigint not null, forma_pagamento_id bigint not null)
create table usuario (id  integer, data_cadastro datetime not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id))
create table usuario_grupo (usuario_id bigint not null, grupo_id bigint not null)
create table cidade (id  integer, nome varchar(80) not null, estado_id bigint not null, primary key (id))
create table cozinha (id  integer, nome varchar(60) not null, primary key (id))
create table estado (id  integer, nome varchar(80) not null, primary key (id))
create table forma_pagamento (id  integer, descricao varchar(255) not null, primary key (id))
create table grupo (id  integer, nome varchar(255) not null, primary key (id))
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null)
create table item_pedido (id  integer, observacao varchar(255), preco_total numeric(19,2) not null, preco_unitario numeric(19,2) not null, quantidade integer not null, pedido_id bigint not null, produto_id bigint not null, primary key (id))
create table pedido (id  integer, codigo varchar(255) not null, data_cancelemento datetime, data_confirmacao datetime, data_criacao datetime not null, data_entrega datetime, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), status integer, subtotal numeric(19,2) not null, taxa_frete numeric(19,2) not null, valor_total numeric(19,2) not null, usuario_cliente_id bigint not null, endereco_cidade_id bigint, forma_pagamento_id bigint not null, restaurante_id bigint not null, primary key (id))
create table permissao (id  integer, descricao varchar(255) not null, nome varchar(255) not null, primary key (id))
create table produto (id  integer, ativo boolean not null, descricao varchar(255) not null, nome varchar(255) not null, preco numeric(19,2) not null, restaurante_id bigint not null, primary key (id))
create table restaurante (id  integer, aberto boolean, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, taxa_frete numeric(19,2) not null, cozinha_id bigint not null, endereco_cidade_id bigint, primary key (id))
create table restaurante_forma_pagamento (restaurante_id bigint not null, forma_pagamento_id bigint not null)
create table usuario (id  integer, data_cadastro datetime not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id))
create table usuario_grupo (usuario_id bigint not null, grupo_id bigint not null)
create table cidade (id  integer, nome varchar(80) not null, estado_id bigint not null, primary key (id))
create table cozinha (id  integer, nome varchar(60) not null, primary key (id))
create table estado (id  integer, nome varchar(80) not null, primary key (id))
create table forma_pagamento (id  integer, descricao varchar(255) not null, primary key (id))
create table grupo (id  integer, nome varchar(255) not null, primary key (id))
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null)
create table item_pedido (id  integer, observacao varchar(255), preco_total numeric(19,2) not null, preco_unitario numeric(19,2) not null, quantidade integer not null, pedido_id bigint not null, produto_id bigint not null, primary key (id))
create table pedido (id  integer, codigo varchar(255) not null, data_cancelemento datetime, data_confirmacao datetime, data_criacao datetime not null, data_entrega datetime, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), status integer, subtotal numeric(19,2) not null, taxa_frete numeric(19,2) not null, valor_total numeric(19,2) not null, usuario_cliente_id bigint not null, endereco_cidade_id bigint, forma_pagamento_id bigint not null, restaurante_id bigint not null, primary key (id))
create table permissao (id  integer, descricao varchar(255) not null, nome varchar(255) not null, primary key (id))
create table produto (id  integer, ativo boolean not null, descricao varchar(255) not null, nome varchar(255) not null, preco numeric(19,2) not null, restaurante_id bigint not null, primary key (id))
create table restaurante (id  integer, aberto boolean, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, taxa_frete numeric(19,2) not null, cozinha_id bigint not null, endereco_cidade_id bigint, primary key (id))
create table restaurante_forma_pagamento (restaurante_id bigint not null, forma_pagamento_id bigint not null)
create table usuario (id  integer, data_cadastro datetime not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id))
create table usuario_grupo (usuario_id bigint not null, grupo_id bigint not null)
create table cidade (id  integer, nome varchar(80) not null, estado_id bigint not null, primary key (id))
create table cozinha (id  integer, nome varchar(60) not null, primary key (id))
create table estado (id  integer, nome varchar(80) not null, primary key (id))
create table forma_pagamento (id  integer, descricao varchar(255) not null, primary key (id))
create table grupo (id  integer, nome varchar(255) not null, primary key (id))
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null)
create table item_pedido (id  integer, observacao varchar(255), preco_total numeric(19,2) not null, preco_unitario numeric(19,2) not null, quantidade integer not null, pedido_id bigint not null, produto_id bigint not null, primary key (id))
create table pedido (id  integer, codigo varchar(255) not null, data_cancelemento datetime, data_confirmacao datetime, data_criacao datetime not null, data_entrega datetime, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), status integer, subtotal numeric(19,2) not null, taxa_frete numeric(19,2) not null, valor_total numeric(19,2) not null, usuario_cliente_id bigint not null, endereco_cidade_id bigint, forma_pagamento_id bigint not null, restaurante_id bigint not null, primary key (id))
create table permissao (id  integer, descricao varchar(255) not null, nome varchar(255) not null, primary key (id))
create table produto (id  integer, ativo boolean not null, descricao varchar(255) not null, nome varchar(255) not null, preco numeric(19,2) not null, restaurante_id bigint not null, primary key (id))
create table restaurante (id  integer, aberto boolean, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, taxa_frete numeric(19,2) not null, cozinha_id bigint not null, endereco_cidade_id bigint, primary key (id))
create table restaurante_forma_pagamento (restaurante_id bigint not null, forma_pagamento_id bigint not null)
create table usuario (id  integer, data_cadastro datetime not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id))
create table usuario_grupo (usuario_id bigint not null, grupo_id bigint not null)
